### ISSUE TITLE
Error in Archlinux 64 bits

### ISSUE THREAD

**Issue by shini-kire** [KillaW0lf04/The-Witcher-2-Issues#91] opened 2015-01-21 01:10 UTC
-> http://steamcommunity.com/app/20920/discussions/0/616199347863659881/
-> https://steamcommunity.com/linkfilter/?url=http://pastebin.com/4nvbnTF8

hello guy!  i'm using archlinux 64bits and sorry my english is really bad :((  i'm from chile, i speak spanish :S

![i-nex - cpu_003](https://cloud.githubusercontent.com/assets/1254844/5829431/da3c88ca-a0f0-11e4-87f3-c699d104df99.png)
![i-nex - gpu_001](https://cloud.githubusercontent.com/assets/1254844/5829432/da3e7f72-a0f0-11e4-8bd7-16293dd9a9c1.png)
![i-nex - gpu_002](https://cloud.githubusercontent.com/assets/1254844/5829433/da409b0e-a0f0-11e4-9442-a77e3ac6088e.png)

and upload this video: steam://openurl/https://www.youtube.com/watch?v=eEcekZcwkcY&feature=youtu.be

**Comment by licaon-kter** [comment] 2015-01-21 08:10
Can you try to start it on the nVidia card ( via de Steam command line I presume)? The log says it tried to use the Intel one.

**Comment by FrostbittenKing** [comment] 2015-01-21 13:16
Duplicate bug. https://github.com/KillaW0lf04/The-Witcher-2-Issues/issues/89.
Please close. Can't people check the other threads before posting redundant bug reports?

**Comment by vpltd-peterm** [comment] 2015-01-21 15:18
Closed as duplicate of #89

**Closed by vpltd-peterm** 2015-01-21 15:18 UTC
