### ISSUE TITLE
Meditate Menu and D-pad not working on xbox wireless pad

### ISSUE THREAD

**Issue by psychoraz** [KillaW0lf04/The-Witcher-2-Issues#94] opened 2015-01-28 21:30 UTC
Arch linux, using linux_public_beta.
Tried xpad, xboxdrv and steamos-xpad-dkms. 

Nothing happens when pressing/holding LT. Tried to press/hold every button on the pad, no quick menu/meditation menu appeared.
D-pad is also not working, to access inventory I must go through the "pause" menu.

**Comment by lothmordor** [comment] 2015-01-29 20:31
Gentoo linux and using a PS3 controller.
Also seeing the problem with the left trigger button.  The User.ini file entry for it is:
 IK_Pad_LeftTrigger=(GameKey=GI_FastMenu,Value=1.000000)
"FastMenu" still failed to open after remapping key to the right trigger instead.
Menu will open with the keyboard entry though:
IK_LControl=(GameKey=GI_FastMenu,Value=1.000000)
Maybe there is a typo in the code for parsing gamepad input?

**Comment by RATINCAGE** [comment] 2015-01-31 14:44
I'm having very similar issues to psychoraz, except that I am using Manjaro XFCE. I am using as wired Xbox360 controller as well. I tried xboxdrv also and it did not work. My LT is working fine in other games and the LT button is registering okay with jtest. All the other buttons work okay. WHen I go into the controller config quick menu is alreayd set to LT. If I click to set quick menu and pull LT again it seems to cycle randomly between Left Stick H, Left Stick V, IK_Pad...htAxisY, and LT. All the other buttons on the controller remap properly.

**Comment by asavah** [comment] 2015-02-04 20:37
Im having the same issue.
Ubuntu 15.04 + vanilla kernel 3.19-rc7.
Tried xboxdrv 0.8.5 - problem exists.
Tried xboxdrv 0.9.0 build from git sources - problem exists.
Tried kernel xpad driver - same problem.

After investigating a little bit I found that:
Release version does not exhibit this problem.
The _button_ doesn't matter - if I remap in game's input settings "block" to LT - blocking works, even remapped to any other button "fast menu" does NOT work.

It's a game issue not controller itself or driver related.

**Comment by vpltd-peterm** [comment] 2015-02-06 03:18
The problem seems to be that the SDLGamepad.config we shipped is out of date. Please try deleting or renaming it and see what happens.

Also try with mappings from https://github.com/gabomdq/SDL_GameControllerDB. One thing I have noticed though is that the SDL2 library in steam-runtime only wants to load mappings indicated for Linux. If the mapping doesn't have "platform:linux", it is ignored.

**Comment by asavah** [comment] 2015-02-06 13:27
@vpltd-peterm I already tried deleting  SDLGamepad.config
Nothing changed.
I've tried several times remapping the controller from within the big picture mode too, same result.

As soon as I get home I'll try the other mappings you suggested and post the result.

**Comment by asavah** [comment] 2015-02-06 19:56
@vpltd-peterm 
Tried everything again - no luck.
The bug seems to be in the game code itself.

In big picture mode every single button works fine.
In game the buttons work fine too.
It's "fast menu" which is failing to show, I don't have issues with D-pad as OP did.
I'll explain again:
If I remap in launcher's input settings "block" to LT and "fast menu" to RT - blocking works on LT button, fast menu on RT does not work.
It does't matter to which button I remap fast menu - it won't show, I tried *every* button it would allow me to use.
So the game actually "sees" every button just fine, but somehow fast menu fails when triggered from controller.
Every other mapping works no matter the button I assign it to.
Fast menu works fine if I press keyboard CTRL key.
In options the input *is* set to controller.

The problem is within the beta version of the *game* , not steam, SDL or phase of the moon.
On RELEASE version everything works fine.

**Comment by vpltd-peterm** [comment] 2015-02-06 21:08
OK, I have found out it was a combination of things - an incorrect mapping in our SDLGamepad.config, and a workaround in code for that incorrect mapping.

I have corrected both, and the pad should work correctly in the next beta

**Comment by asavah** [comment] 2015-02-06 21:51
@vpltd-peterm 
TY
The build 517988 just arrived in steam.
Fixes the issue for me.

**Comment by psychoraz** [comment] 2015-02-06 22:02
Seems fixed on my end too :)
Thanks to everyone, specially to asavah for all the feedback i didn't provide, and to Peter from VP, for fixing this so quickly.

**Closed** 2015-02-06 22:02 UTC
