### ISSUE TITLE
Game does not start: PrepareOpenGLDisplayInformation() failed

### ISSUE THREAD

**Issue by khnazile** [KillaW0lf04/The-Witcher-2-Issues#96] opened 2015-01-29 04:52 UTC
I'm not sure if it is an issue with the game, or i've misconfigured my system, but I cannot find anything related in Google.
I'm running openSUSE 13.2 x86_64 with Mesa video drivers. Other people reported games works with Mesa, and I believe I was able to start it some time ago, but now it does not start. It does not crashes, it just silently quits after launcher.

Here is my eon.txt:
[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][0]: Default allowed number of simultaneously open files in the system is 2448.
[thread ffffffff][I][0]: Current memlock limit is 65536.
[thread ffffffff][I][0]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread ffffffff][I][3]: setup_teb_register() - using LDT entry 13
[thread 00000001][E][165]: PrepareOpenGLDisplayInformation() failed!!

I've tried installing beta from steam, it does not help.

**Comment by vpltd-peterm** [comment] 2015-01-29 10:58
Duplicate of #93

**Closed by vpltd-peterm** 2015-01-29 10:58 UTC
