### ISSUE TITLE
Crash on Start On Fedora 20/21 With Strange Error Message

### ISSUE THREAD

**Issue by DylanDonkersgoed** [KillaW0lf04/The-Witcher-2-Issues#88] opened 2015-01-11 00:36 UTC
When I try to start the game on Fedora 21 from the command line with:

```bash
~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh ./witcher2
```
(from ~/.steam/steam/SteamApps/common/the witcher 2)

I get this error message:

```bash
witcher2: /mnt/Storage/Development/Projects/eon2-witcher2/src/dlls/win32/kernel32/winthreads.cpp:308: int get_selector_for_teb_entries(): Assertion `ret == 0' failed.
```

The full output is here: https://gist.github.com/DylanDonkersgoed/b2386127e9c099eb2a17
I've found only one other instance of this happening by searching with no answer there.

Here's the output from the actual error report: https://gist.github.com/DylanDonkersgoed/4341602d794b17b27f07

I'll note that I've had the same issues on Fedora 20 with the open source graphics driver, 21 with the open source driver, and 21 with the proprietary driver. 

My system specs as reported by Steam are:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.17.7-300.fc21.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11602901
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-08-20
    
Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7600M Series

    Driver Version:  4.4.13283 Compatibility Profile Context 14.501.1003
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6840
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 2646 x 1024
    Primary Display Size: 13.54" x 7.64"  (15.51" diag)
                                            34.4cm x 19.4cm  (39.4cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC269VB
    
Memory:
    RAM:  7947 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  460033 Mb
    Largest Free Hard Disk Block:  148982 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by nobrakal** [comment] 2015-01-20 15:20
I have the same issue, with or without the steam runtime, on my Fedora 21 Workstation edition. Any updates ? Here the full crash log https://gist.github.com/nobrakal/b094c95a9572822b255f

Here my system spec:
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3500 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Fedora release 21 (Twenty One)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.17.8-300.fc21.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11602901
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TURKS

    Driver Version:  1.4 (3.0 Mesa 10.4.1)
    OpenGL Version: 1.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 75 Hz
    VendorID:  0x1002
    DeviceID:  0x6758
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1280 x 1024
    Desktop Resolution: 1280 x 1024
    Primary Display Size: 14,80" x 11,85"  (18,94" diag)
                                            37,6cm x 30,1cm  (48,1cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: VIA VT1705
    
Memory:
    RAM:  3936 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  fr_FR.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  410776 Mb
    Largest Free Hard Disk Block:  177843 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by vpltd-peterm** [comment] 2015-01-20 15:36
Duplicate of issue #89

**Closed by vpltd-peterm** 2015-01-20 15:36 UTC

**Comment by rubencarneiro** [comment] 2015-03-18 18:12
Just worked on mine updating to the latest patch.
Running Ubuntu 14.04
3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
